### PR TITLE
Improve Linux font paths

### PR DESCRIPTION
**Pull request by lhupe**
This PR adds the standard path fo user fonts in modern Linux desktop systems, as well as fixing the existing `~/.fonts` path.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Did you make sure somehow, that this works ?

**Comment by lhupe** [comment]
Yes, I did (on two different Linux systems). However, originally, I only checked for a font installed in a subdirectory of `~/.local/share/fonts/`. I just repeated my test with a font installed directly to `/.fonts` and noticed that while all subdirectories of the specified directories are added to the font path list, the directory itself is ignored. My latest commit should fix this.

**Comment by lhupe** [comment]
is there anything that still needs to be done before this is merged?

**Comment by SimonDanisch** [comment]
Oh, I guess I was just waiting for the CI to go green after your changes :D

**Pull request merged**
