### PR TITLE
Fix character spacing in `renderstring!`

### PR DESCRIPTION
**Pull request by ffreyer**
Running 
```julia
# render a string into an existing matrix
face = findfont("Dejavu Sans")
pixelsize = 64
x0, y0 = 2, 0
myarray = zeros(UInt8, pixelsize+2, 23pixelsize)
renderstring!(
    myarray, "0123456789qwertzuiopasdfghjklyxcvbnm,.-", face, pixelsize, 
    x0, y0, valign = :vtop
)

scene = Scene(resolution = (size(myarray, 2), size(myarray, 1)))
campixel!(scene)
heatmap!(scene, myarray'[:, end:-1:1], colormap = (:white, :black))
Makie.save("/home/frederic/Desktop/old.png", scene)
```

currently generates

old

because the horizontal bearings are applied in the wrong direction. With these changes I get

new

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Interesting, that this creates some artifacts:
image

**Comment by ffreyer** [comment]
I've noticed that too, but I don't think that's because of this change. If you look at x or v you can see artifacts in both, but they move a little between the two versions.

**Comment by ffreyer** [comment]
Saving just `v` from a 64px render with FileIO:
v_fileio
with Makie heatmap:
v_makie

**Comment by SimonDanisch** [comment]
Interesting...

**Comment by ffreyer** [comment]
Oh right - that's because heatmaps are shifted by 0.5. Translating the plot to integer values removes these artifacts.
new_shifted

**Pull request merged**
