### PR TITLE
move to Project file

### PR DESCRIPTION
**Pull request by KristofferC**
Also allows FreeType v3 to be used

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Hm, I guess the failure is simply, because travis windows has different fonts installed -.-

**Comment by SimonDanisch** [comment]
I'd say remove windows from travis for now, or figure out what needs to be removed from: https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/blob/master/test/runtests.jl#L81

**Comment by KristofferC** [comment]
Done

**Comment by SimonDanisch** [comment]
Thanks a lot! :)

**Pull request merged**
