### PR TITLE
apply patches from GLVisualize

### PR DESCRIPTION
**Pull request by bjarthur**
i didn't include `force_ucs2_charmap` or `FontFace` because they appeared not to be used in FreeTypeAbstraction or GLVisualize.  let me know if you'd prefer to retain them.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
No that's perfect! I also wanted to remove them in GLVisualize but didn't get to it...

**Comment by bjarthur** [comment]
tests are passing on 0.5

**Comment by bjarthur** [comment]
hmmm....  i didn't patch `__init__` from GLVisualize.  should we port that too so users don't have to manually call `init` and `done`?

**Comment by SimonDanisch** [comment]
Yes! :)

**Comment by SimonDanisch** [comment]
So just add the `__init__` and I can merge ;)

**Comment by bjarthur** [comment]
__init__ added, but let me use this in practice a bit before you merge

**Comment by bjarthur** [comment]
this is ready to merge i think unless anyone has comments

**Comment by SimonDanisch** [comment]
Can we deactivate tests on 0.6, or switch to StaticArrays? The switch should very straightforward ;)

**Comment by bjarthur** [comment]
added another commit to switch to StaticArrays.  tests have already passed on linux; waiting to start on os x,  where they work locally

**Comment by SimonDanisch** [comment]
Great! :)

**Comment by bjarthur** [comment]
all tests have passed

**Pull request merged**
